### ISSUE TITLE
Diaspora protocol disabled by default

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla-addons#1]
When enabling the Diaspora protocol system wide, new channels still have Diaspora disabled in the 'Diaspora Protocol Settings'. 

Two questions:

1. Should Diaspora not be enabled for new channels after enabling the plugin?

2. If not, how to make sure it is enabled on my hub for all new channels?

**Comment by redmatrix** [comment]
Nomadic identity is default behaviour and a core feature. Diaspora support is not. Out of the box we need to provide an environment where our base feature set works and doesn't include two features which conflict with each other - as these do. It should remain optional. You could create an addon to enable it automatically on channel creation (use the incorrectly named 'register_account' hook to trigger setting the pconfig). I'm going to rename that to 'create_identity' right now so I don't forget.

**Comment by jeroenpraat** [comment]
I think we misunderstand each other. I totally understand and agree about the Diaspora protocol not for in core. But is it not logical that when a hub admin decides to enable the Diaspora protocol addon, he/she can expect the protocol is enabled by default for new channels. Or at least have an option for the hub admin (in the admin addon settings or via util/config) to enable the protocol by default for new channels.

**Comment by redmatrix** [comment]
There is currently no way to do that except to create an addon to turn it on for new channels. Diaspora is fundamentally incompatible with hubzilla and this results is a huge support burden which detracts from our core mission. That is the bottom line - incompatible and unsupported.
