### ISSUE TITLE
Some remarks about the Embedly plugin

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla-addons#14]
- The plugin now is broken
- Oohembed.com is now embed.ly and needs an API
- The free API only takes 5000 embeds per month, so we need a hub or even better a channel configuration for providing that API.
- Does embed.ly fits in our privacy aware platform?

**Comment by jeroenpraat** [comment]
Maybe we need a embedly alternative, that better fits Hubzilla's vision.

**Comment by redmatrix** [comment]
I'd be OK if it's removed. It was part of "core" in Friendica and I moved it to a plugin in Redmatrix and nobody really  uses it that I'm aware of. The core oembed code seems to work ok for the major media providers. Alternatively, put "obsolete" in the description so admins don't try and install it. This way we could keep the existing code as an example for writing oembed plugins.

**Comment by jeroenpraat** [comment]
I will take a look at it tomorrow if I can find a suitable alternative. The code is indeed a good example, so when I have something workable I will remove this one. 

I'm keeping this issue open till than.

**Comment by jeroenpraat** [comment]
This one is very attractive: http://noembed.com/

**Comment by jeroenpraat** [comment]
Created a Noembed plugin, but somehow nothing happens. @redmatrix Is oembed_probe valid? And are the variables in the noembed_oembed_probe function also valid?

**Comment by jeroenpraat** [comment]
This works: https://noembed.com/embed?url=https://en.wikipedia.org/wiki/David_Bowie

**Comment by jeroenpraat** [comment]
Thanks Mike, the noembed plugin now works!
