### ISSUE TITLE
Diaspora - Can't update profile avatar

### ISSUE THREAD

**Issue by DeadSuperHero** [redmatrix/hubzilla-addons#3]
Figured I'd open an issue for this; I assume that this would be the best place to do so, given that this issue seems to be specific to Diaspora (but also could be a byproduct of my transition from RM -> HZ)

So, my avatar is not reflected in Diaspora. Posts federate, comments federate, even messages come through without issue. However, I've tried to update my avatar several times, and a change does not appear to register on the Diaspora-facing side of things.

Diaspora:
![sean_tilley](https://cloud.githubusercontent.com/assets/401560/11043511/abe37366-86e2-11e5-8b44-29ef6f24a544.png)

Hubzilla:
![sean_tilley_-_sean_deadsuperhero_com](https://cloud.githubusercontent.com/assets/401560/11043532/c86f4406-86e2-11e5-9c52-f84f384a2d35.png)

**Comment by DeadSuperHero** [comment]
Curiously, the new avatar seems to be fetched for new connections on pods that haven't discovered me before: https://diaspora.kosebamse.com/posts/170654a069450133941a001c4202e28a

![my_first_contact_with__diaspora_was_setting_up_my_own_pod__so_i_am_](https://cloud.githubusercontent.com/assets/401560/11045473/57b30616-86ed-11e5-9a38-bec7884757f2.png)

**Comment by redmatrix** [comment]
It appears that the diaspora "profile update" message wasn't implemented in redmatrix or hubzilla, for various reasons. An oversight. I've (just) added the code back in, but you may need to "change your profile" (no change is required, but saving it triggers the remote updates) to push the changes. I can't really test this as my current hub doesn't work with Diaspora at all. Anyway it may need further work, but at least the code is now present and I've confirmed it was missing.
