### ISSUE TITLE
Unclear documentation for last step of GNU social integration

### ISSUE THREAD

**Issue by ivilata** [redmatrix/hubzilla-addons#42]
The [documentation of the statusnet addon](https://github.com/redmatrix/hubzilla-addons/blob/master/statusnet/README) (as of version 1.14.2) states in its last paragraph:

> After the required credentials for the application are stored in the configuration you have to actually connect your Hubzilla channel with GNU social. To do so follow the Sign in with GNU social button[…]

However, it is not clear where that button is located.  In my case at least it is not in the plugin's admin page. Thanks!

**Comment by zotlabs** [comment]
This documentation is actually older than Hubzilla. 

Your channel Settings -> Feature/Addon Settings -> GNU social Post Settings

The top level Settings menu can be accessed from the menu attached to your photo in the navbar. 

This "GNU social Post Settings" has several states it can be in. If the Hubzilla site admin provides an OAuth token we will use that and proceed to ask you to connect. If there is no site token, you will need to register a client on GNU-Social and provide the auth details here, and then the next time you visit these settings the form changes to ask you to connect. 

Once connected, this settings sub-section changes once again to provide application settings and allow you to logout or discard the authentication credentials. Overall, the usability of this feature admittedly sucks, but once connected you shouldn't have to mess with it.

**Comment by ivilata** [comment]
Thanks @zotlabs for the quick reply. I already registered the client in GNU social and added the site to statusnet plugin in admin settings, so the channel configuration was the only thing left.

However when I visit channel Settings -> Feature/Addon Settings (``SITE/settings/featured``) I get a blank page with a 500 Internal Server Error HTTP code. The error log entry shows:

```
2016/11/17 08:00:56 [error] 4277#0: *248875 FastCGI sent in stderr: 
 "PHP message: PHP Fatal error:  Call to a member function get_baseurl() on integer in 
 <PATH>/hubzilla/extend/addon/matrix/statusnet/statusnet.php on line 277" 
 while reading response header from upstream, client: <IP>, server: <SERVER>, 
 request: "GET /settings/featured HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", 
 host: "<SERVER>", referrer: "https://<SERVER>/settings/features"
```

The line is the third one under ``function statusnet_settings(&$a,&$s)``, which includes a call to ``$a->get_baseurl()``. Shall I report an issue to ``hubzilla-addons``?

**Comment by zotlabs** [comment]
We haven't used $a->get_baseurl since much earlier this year and I cannot locate that call in current code. I'd recommend git pull hubzilla-addons and use a recent version of the plugin.

**Comment by ivilata** [comment]
Oh, so it failed to work because I forgot to update the addons checkout, shame on me! I tried again with an updated checkout and it worked without issues (yes, the settings UI is a bit strange).

Well, sorry for the noise and thank you very much for your quick attention. ``:)``
