### ISSUE TITLE
Twitter plugin configuration UI incomplete

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla-addons#5]
The Twitter plugin looks like it needs some attention. The configuration for the API keys looks like it was intended to be in the UI, but it's not there, it's only available from the command line.

Moved here from https://github.com/redmatrix/hubzilla/issues/162 for OCD reasons.

This should be retested (there's no retest-please label in this repo)

@spukkin yo, can you try?

**Comment by jeroenpraat** [comment]
I think it will also a good idea to have the consumerkey+secret on a user level. As a hub owner I don't want to use my Twitter account for all hub members.

**Comment by kenrestivo** [comment]
That seems reasonable. Again, maybe the admin can set one, users can override it, or if the admin doesn't set one, the user must supply it?

**Comment by jeroenpraat** [comment]
I think the best way to do it is your first option, but I like to put it another way: make it possible for a user to supply their personal OAuth configuration, but when an admin supplies a hub/system wide OAuth configuration the user can use that by toggle something like "Use the hub administrators OAuth configuration". If an hub admin didn't set an OAuth config, the toggle should not be there, so the user always has to enter its OAuth config.

**Comment by rodneyrod** [comment]
Will there be any attempt to port the read timeline feature that's in the Friendica plugin at all?
