### ISSUE TITLE
Diaspora: Comments from unknown persons are not accpted

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla-addons#68]
There seems to be an issue with comments from Diaspora on public posts. Compare here https://pod.geraspora.de/posts/7051830 with here: https://hubzilla.online/channel/holger/?f=&mid=bf872eae0d515956e81cd35642ca84f706042c292e2ff8b830d9cc4936ca6d68@hubzilla.online

The comment from "Kim Jong Double Fuck" didn't arrived.

I guess that it is the same issue that we had on Friendica. Have a look at the public dispatcher: https://github.com/redmatrix/hubzilla-addons/blob/master/diaspora/inbound.php#L6

It looks at the author and then distributes the post to the channel. Problem is that comments can come from users that aren't connected to any channel. So there has to be a check if the action is a "like" or "comment" and then has to look for the parent to find the associated channel.

**Comment by git-marijus** [comment]
Keep in mind that there is a channel setting to enable public comments from diaspora (which is on by default iirc).
