### ISSUE TITLE
wppost - unable to post - offer User-Agent to Wordpress.com to post

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla-addons#7]
http://stackoverflow.com/questions/25329426/xml-rpc-failing-to-respond-to-post-requests-via-curl-in-php suggests wppost-plugin needs to offer a "User-Agent" to post to Wordpress.com.

"Managed to fix it. Looking at the headers sent by cURL, the only differences were that the cURL command line uses Content-Type: application/x-www-form-urlencoded and that the user agent was set to User-Agent: curl/7.30.0.

The choice of content type didn't affect it, but setting a user agent sorted it! It seems WordPress.com (but not self-hosted WordPress.org sites running the latest v3.9.2) now requires a user agent for XML-RPC requests, though this hasn't been documented anywhere that I can find."

**Comment by zotlabs** [comment]
The user-agent has been sent for ages. What was probably missing was the 'blog-id' parameter for XMLRPC. This was added to the plugin a month or two ago.  If it is still broken after setting the correct blog-id, please re-open.
