### ISSUE TITLE
GNU-Social: delayed post setting not regarded

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla-addons#74]
Works for diaspora and friendica but not for gnu-social.
If activitypub is also affected needs to be investigated.

This issue has been reported to me. Have not tested anything myself yet.

**Comment by zotlabs** [comment]
Fixed in red master 1d4d0cd

**Comment by hfroese** [comment]
It is unfortunately not fixed yet. Still the same behavior.

**Comment by git-marijus** [comment]
I can have a look at it as soon as my hub will be up again. That mught take another 10 days though :|

**Comment by hfroese** [comment]
Good luck

**Comment by git-marijus** [comment]
Meh... Just needs a restart but i can't get there atm...

**Comment by hfroese** [comment]
Relax my friend and enjoy christmas holidays.

**Comment by zotlabs** [comment]
I was able to duplicate the issue originally, but after patching with the referenced checkin I am unable to duplicate. Future posts are synced to clones but are blocked/rejected from all normal deliveries until the scheduled date passes.

**Comment by git-marijus** [comment]
And that was only this checkin https://github.com/redmatrix/hubzilla/commit/c087d1e18b32f62d126cb01accbdeff21f5c1107 right?

**Comment by zotlabs** [comment]
Correct. I've also verified @hfroese site has been updated.

**Comment by hfroese** [comment]
Tested again. May be there's a conetxt or not but:
time set to 13:00 - works
time set to 12:36 - doesn't work
time set to 14:00 - works
time set to 13:15 - works
time set to 12:47 - doesn't work

**Comment by zotlabs** [comment]
There is a built-in "slop" or "fudge factor" of ten minutes into the future. This way if your clock is *slightly* off your posts won't vanish. That would be bad. Anything more than ten minutes into the future is delayed.

**Comment by hfroese** [comment]
Ah - okay. So everything works fine now. Thanks

**Comment by hfroese** [comment]
All delayed posts aren't federated to diaspora anymore.
GNU-Social and Friendica works well.
