### ISSUE TITLE
Chess addon - random color

### ISSUE THREAD

**Issue by mrjive** [redmatrix/hubzilla-addons#76]
Hey there!
It would be nice to have the choice to randomize the color of the new game. What do you think?

**Comment by mrjive** [comment]
I tried this and it seems to work..
file: chess.php
from line 367

/*
                                                notice(t('You must select white or black.') . EOL);
                                                return;
*/
                                                $randomValue = mt_rand();
                                                ($randomValue % 2 == 0 ? $color="white" : $color="black");
                                                notice(t('Random color chosen.') . EOL);

**Comment by anaqreon** [comment]
https://github.com/redmatrix/hubzilla-addons/pull/77
