### ISSUE TITLE
Link to game (and position)

### ISSUE THREAD

**Issue by mrjive** [redmatrix/hubzilla-addons#79]
For every move a comment to the game post is generated with the fen position.
Since games cam be long, it is not very handy, once you click the link in the notification (mail or website), being taken to the comment and then, to reach the actual game, to scroll back to the top and click on the link.
So I suggest to add a "click here to play" to every post
OR (even better)
add a link for every position that brings you to the corresponding position.

**Comment by anaqreon** [comment]
I added a link to the game in each move comment: https://github.com/redmatrix/hubzilla-addons/commit/ba119e748d13df36bd91576f1790fb71d4b16f60

**Comment by mrjive** [comment]
What about the direct link to the single position? :P

**Comment by anaqreon** [comment]
"An exercise for the reader"
