### ISSUE TITLE
Metatags Plugin 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla-addons#9]
I make a simple metatags plugin for solve Hubzilla issue #211
The plugin can be configure in .htconfig.php us wish of the admin
https://github.com/royalterra/release

Feel free to include. The plugin Can be check working again the domain blablanet.com
Simple write site:blablanet.com for show the Crawl by the search Engine now show personalize
Description

**Comment by redmatrix** [comment]
Please provide a pull request

**Comment by royalterra** [comment]
Done Thanks
